context:
  version: "2.1.0"

package:
  name: evalidate
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/e/evalidate/evalidate-${{ version }}.tar.gz
    sha256: f46e12e5549c264438bbfd4f60a0b83ec0289bdca11a01b48a1c999f8c6fe5ce

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.27.0
    - wheel
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - evalidate
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Validation and secure evaluation of untrusted python expressions
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/yaroslaff/evalidate
  repository: https://github.com/yaroslaff/evalidate

extra:
  recipe-maintainers:
    - jaimergp
