context:
  version: "2.0.4"

package:
  name: evalidate
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/e/evalidate/evalidate-${{ version }}.tar.gz
    sha256: adcdb08674dfa21fbf590ddc8cba5d21e35a21585e9ff487960a2035a2fbb8c4

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - wheel
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - evalidate
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Validation and secure evaluation of untrusted python expressions
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/yaroslaff/evalidate
  repository: https://github.com/yaroslaff/evalidate

extra:
  recipe-maintainers:
    - jaimergp
